### ISSUE TITLE
where can i find teh newest driver?

### ISSUE THREAD

**Issue by orbitalsupershell** [snakeMax/KahootBotter#1]

**Comment by orbitalsupershell** [comment]
becouse i cant run it it gives this
PS C:\Users\Gebruiker\Documents\code\github\downloaded\KahootBotter-master> python .\main.py
Welcome to Kahoot Flooder by xTobyPlayZ - Copyright (c) 2021
Game Pin: 7730744
1) Custom names
2) Random names
Choose an option: 1
Bot Name: chinatown
Bot Amount: 100
Sending 100 bots...
C:\Users\Gebruiker\Documents\code\github\downloaded\KahootBotter-master\main.py:66: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path=PATH, options=options)
Traceback (most recent call last):
  File "C:\Users\Gebruiker\Documents\code\github\downloaded\KahootBotter-master\main.py", line 66, in <module>
    driver = webdriver.Chrome(executable_path=PATH, options=options)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Gebruiker\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        Ordinal0 [0x00C0BDE3+2473443]
        Ordinal0 [0x00BA6661+2057825]
        Ordinal0 [0x00AB2438+1057848]
        Ordinal0 [0x00ACB62C+1160748]
        Ordinal0 [0x00AC9CAF+1154223]
        Ordinal0 [0x00AF9ADF+1350367]
        Ordinal0 [0x00AF974A+1349450]
        Ordinal0 [0x00AF55AB+1332651]
        Ordinal0 [0x00AD2104+1188100]
        Ordinal0 [0x00AD2F59+1191769]
        GetHandleVerifier [0x00D92266+1549718]
        GetHandleVerifier [0x00E3D4A7+2250711]
        GetHandleVerifier [0x00C9718B+521403]
        GetHandleVerifier [0x00C96229+517465]
        Ordinal0 [0x00BAB79D+2078621]
        Ordinal0 [0x00BAFB58+2095960]
        Ordinal0 [0x00BAFC92+2096274]
        Ordinal0 [0x00BB9541+2135361]
        BaseThreadInitThunk [0x773CFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77677A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77677A6E+238]

**Comment by snakeMax** [comment]
https://chromedriver.chromium.org/downloads
Make sure to place it in chromedriver folder, with correct name

**Comment by orbitalsupershell** [comment]
It works! (A bit inefficent with joining but thanks for the help!)
